### PR TITLE
.Net Standard 2.0 Support

### PR DESCRIPTION
**Pull request by Aragas**
.Net Standard does not have any WMI support, but it is needed for getting information like hardware.
For an example, see my library https://github.com/Aragas/SystemInfoLibrary
It looks like it would work fine, but there is this WMINet_Utils.dll dependency that is not included in .Net Core 2.0 runtime, so we need to copy it from .Net Framework. I took both of them from v2.0.50727. Not sure if we are even allowed to do it tho.
Btw. Is there a way to remove this dependency?

### CODE REVIEW

**Comment by MartinKuschnik** [comment]
Hi Aragas,

it should be possible to implement a switch for .Net Framework 2.0.

[Version 1.0](https://www.nuget.org/packages/WmiLight/1.0.7-PreRelease29342) of this library (not available on github) was implemented in this way.

I used the WMINet_Utils lib because Microsoft does some magic to speed up the connection creation.

I will have a look to that.

**Comment by MartinKuschnik** [comment]
I think i misunderstood the use case .

Do you think it makes sense to implement such an operation system depended component like WMI to .Net Core 2.0?

If yes:

I'm not sure if its possible to ship the WMINet_Utils.dll. It's possible that this is not allowed for licencing reasons.

It's would be possible to implement a C++/CLI wrapper that makes the WMINet_Utils.dll magic.
But this would make a lot of work.

**Comment by Aragas** [comment]
While WMI is a Windows specific feature, there is no way of obtaining any hardware info via .Net Core for now.
In linux we can use the command line (cat /proc/meminfo, for example), in os x use libc library.
For windows we can use WMI.

I was trying to make WMI work without the proxy, but every time I get the AccessViolationException. I already tried to copy exactly msdn's WMI C++ tutorial, but without any success.
Never had any experience with COM before, so I'm not really sure if I'm even trying correctly.

**Comment by MartinKuschnik** [comment]
> Is there a way to make a WMI wrapper without using any native code?

I don't know any. But im not very experienced in COM and DCOM.

I have to use the [CoSetProxyBlanket](https://msdn.microsoft.com/en-us/library/windows/desktop/ms692692%28v=vs.85%29.aspx).
[This blog post](https://blogs.msdn.microsoft.com/mbend/2007/04/18/cosetproxyblanket-not-supported-from-managed-code/) explains why the P/Invoke call does not work.

Currently I'm very busy and don't have the time to implement the C++/CLI wrapper.

**Comment by Aragas** [comment]
Thanks for the info

**Pull request closed without merging**
